[package]
name = "tdmodeler-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glam = { workspace = true }
tdmodeler-mesh = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }

[dependencies.wgpu]
workspace = true
optional = true

[features]
default = []
gui = ["dep:wgpu"]
